* 200 dias

** tópicos
- rapaz, 200 dias
- as vezes me pego pensando... um dia sonhei com 2 anos de vida
  nômade, entrando até em boa parte da américa latina...
- na época, parecia um bagulho impossível, né...
- mas, parando para ver... 200 dias já é tipo 25% de um projeto de 2
  anos...
- até aqui... Itamaracá, João Pessoa, Pipa, Canoa Quebrada, Fortaleza,
  Jericoacara, São Luís...
- A pergunta que sempre fazem: Qual o favorito? Pipa. Depois, vem João
  Pessoa e Fortaleza... Logo abaixo, Jericoara e São Luís... Os
  últimos são Canoa Quebrada e Itamaracá... Isso quer dizer mais sobre
  a experiência do que a cidade em si... Em são Luís, a gente pegou
  uma rotina boa, ar condicionado... Em Jeri nem ar condicionado
  tinha...
- Agora, a gente tende a entrar mais na Amazônia mesmo...
- As vezes da medo com a minha carreira... Logo depois do carnaval, fiquei preocupadasso
- Ainda sinto que estou aprendendo a lidar com essa vida... O lance de 5 horas me fez mal... Eu enrolava muito
- No fundo, dá, sim, para trabalhar mais... E eu preciso de mais horas
  trabalhando... Para evoluir mais tecnicamente... E para fazer mais
  grana também... Eu tenho ficado quase no vermelho... Gastado mais do que eu ganho e isso é perigoso!
- A minha situação tá meio delicada... John pagando do próprio bolso... Pierre fica reclamando...
- As vezes sinto vontade de ter rotina... Fico sonhando com mesa foda,
  vida organizada, fazendo side jobs para fazer mais dinheiro... Mas,
  será que preciso mesmo ir para lá? Quantas dessas coisas eu já não
  conseguiria daqui mesmo?
- 
