* São Luís, Março de 2022

** Barreirinhas - Apetitizer
   + saindo de jeri, fomos para Barreirinhas passar o carnaval conhecendo os lençóis maranhenses
   + já dá para sentir umas diferenças, acho que, até aqui, o Maranhão
     parece ser a região realmente mais pobre que já vivi
   + existem áreas precárias e pobres em todas as cidades grandes que
     eu já morei: BH, Rio, Recife, Fortaleza...
   + Maranhão parece difernte - até que ponto isso não é preconceito também?
   + umas paradas muito virgem
   + essa parte do Brasil, de Jericoacara para esquerda, é um Brasil
     que pouca gente conhece...
   + MAranhão é nordeste, mas tem hora que tem clima de NORTE! Veja
     barreirinhas e o clima com o Rio...
   + fun fact: eles chamam LANCHA de VOADEIRO
   + fun fact: no Maranhão, AÇAÍ é chamado de JUSSARA... o que é
     engraçado, parece nome de secretária...
   + O trecho de BARREIRINHAS até ATINS é o primeiro trecho que eu,
     como usuário do Google Maps, não consegui visualizar como seria,
     quanto tempo demoraria e etc. Fazendo a parada, acabei
     descobrindo que era perrengue para cacete! Tem que usar 4x4,
     balsa, areia fofa, rio no meio do caminho... Dá para ir de lancha
     também!
   + a vegetação nas dunas dos lençóis é de CERRADO e CAATINGA. Perto
     do Rio, ele vai mudando conforme o tempo vai passando, mas tem
     uma hora que fica MATA DE COCAIS.
   + Rally dos ventos - parada muito sinistra que rola nos lençóis.
    
    
** São Luís
  + Achei que não ia ter surf, chego na cidade: carro com long. Mas,
    poderia ser alguém viajando para o Ceará, por exemplo. Daí a
    pouco, vi um surfista na praia andando com uma prancha e um pico.
  + Achei que não ia ter surf. Já tinha até aceitado essa "verdade".
  + Vai ter surf sim!
  + Arroz de Cuxá - prato típico - um arroz com uma erva e um
    camarãozinho seco
  + Os locais chamam São Luís de "A ILHA"... E é mesmo uma ilha... Uma
    "ilha" quase conectada de forma imperceptível ao continente. Tem
    um rio cortando uma parte.
  + a gente meio que tá fazendo a ROTA DAS EMOÇÕES nos últimos 2
    meses: Jericoacoara, Barra Grande, Delta do Parnaíba, Atins, Santo
    Amaro, Lençóis Maranhenses e muito mais.
  + CF98 - clima de praia, beach volley, beach tennis, seguro, infra
    top e com excelente custo benefício
  + conhecemos o Sérgio, formou na EBAPE emm 1971... Lenda, teve aula
    com o Mario Henrique Simonsen
  + Gafanhoto - restaurante vegetariano TOP
  + Mudança mais rápida que já fizemos: de um hotel (moradia
    temporária em são luís) para o apartamento que vamos ficar em São
    Luís, 40 minutos do começo ao fim!
  + O nosso prédio é um flat em um dos melhores bairros de São
    Luís. Ele parece ser frequentado para prostitutas de
    luxo. Manicure. Esteticista. Cabelereiro. Além disso,
    avisos/política interna com problemas, proibindo visitantes - o
    que beira a ilegalidade.
  + Guaraná Jesus -> uma marca daqui! Depois acabou sendo comprado
    pela coca-cola... Rosa e com Jesus no nome haha
  + Supermercado Mateus, muito top e, de certa forma, barato
  + Siô - abreviatura de Senhor/Sinhô, muito usado no Maranhão
  + Eles também falam Ma, por influência do Ceará!
  + Jack é para dizer que alguém bonitão ou galanteador
  + Orla cagada de são luís, literalmente. Tem muitos coliformes
    fecais. Em geral, eles vão para Lagoa Jensen e, de lá, para o mar
  + Não dá para nadar.
  + Cristina koch astronauta russa, ficou 328 dias no espaço. O que
    fazer quando chegar na terra? Praia, mergulho e surf . Mulher mais
    tempo no espaço até 2019. Sinto falta de surf em são luís. Não é
    tão fácil. Ondas não são tão boas. E tenho dúvidas sobre a
    qualidade da onda. Não está tão simples de alugar prancha
    também...
  + Uma tônica das nossas longas viagens de carro: Casal dentro do
    carro, briga, faz as pazes, briga, faz as pazes, volta felizao das
    viagens. Se a terceira fase da viagem rolar, que seria uma
    aventura automobilística bizarra, ainda mais verdade!
  + Se a gente for de carro para a América do Sul, seria AINDA mais
    bizarro!
  + 
