* 2/3 de Abril em Belém do Pará

** Anotações 
   + A mudança de São Luís para o Pará foi a menor que já
     fizemos... Pouquinhas malas... Sem Kite, sem gato, sem prancha...
   + Foi, realmente, muito rápido. E daria, até, para ser mais rápido ainda
   + Na chegada a Belém de avião já dá para perceber algumas
     diferenças. De cima, vc já vê aqueles rios imensos!
   + A chuva é tão forte que a gente teve que ficar rodeando o
     aeroporto até ela dar um tempo e a gente conseguir parar
   + No Pará, eles chamam chup chup de CHOPP DE FRUTA
   + Estávamos em Belém em dia de REPA... Remo x Paysando... Remo fez
     3x0
   + Deu para ouvir os gritos, grande mobilização. Impressiona porque
     são 2 times da 3rd division Brasileira
   + Taperabá  = Cajá do Pará
   + Eles tem um sotaque chiado que lembra o sotaque que existe no Rio
     de Janeiro e o Português...
   + Assim que chegamos, fomos no Parque Mangal das
     Garças... Doideira, coruja viva, garças...
   + No Pará tem terminal HIDROVIÁRIO (sim, não é rodoviário). Eu
     nunca tinha visto. E tem muita gente que se locomove por meio de
     pequenas lanchas.
   + Dentro do rio, tipo lá no meio, tem um posto ipiranga! Sim, os
     barquinhos, lanchinhas, catamarãs, voadeiras, também precisam de
     gasolina no motor e param, no meio do RJ, para abastecer
   + Transporte em barquinhos é realmente uma parada em Belém
   + Não é por acaso que a Marinha brasileira tem uma grande base em
     Belém. Além do acesso ao mar, tem muito rio gigante relevante
     para adentrar no país.
   + Fomos almoçar no COMBU... Meio que uma ilha fluvial ao lado de
     Belém. Rolê muito doido. Uma mistura de churrasco na laje com
     vida/cultura ribeirinha. Aquela galera que mora ao lado do Rio e
     fica nadando. A água tem uma coloração barrenta. Mas, é
     quentinha. Funciona como uma espécie de praia também da população
     ribeirinha.
   + Quando chove muito, fica sem sinal. Como de costume, choveu por
     enquanto a gente estava almoçando no Combu. Tivemos que esperar a
     chuva passar para pagar! kkkk
   + As chuvas começam do nada e param do nada!
   + A mudança de são luís foi a primeira que a gente fez de
     avião. Chegou a rolar um avião em Dezembro e Janeiro. Mas,
     naquela ocasião, a gente saiu de fortaleza, deixou umas coisas
     lá, passou o final de ano em BH e, depois, voltou para Fortaleza
   + 
   
    

** Chuchup
   + Em Minas, chup chup
   + No Pará, chop de fruta
   + No Maranhão, cremosinho
   + No Ceará, ?
   + No Rio Grande do Norte, Din Din
   + Em Pernambuco, ?
   + Em Alagoas, Flau
   + No Piauí, ?
   + No RJ, sacolé
   + 


