* 2/3 (Dois terços) de Abril em Belém do Pará

** Hard facts
   + quando a cidade foi fundada e tal, tamanho da população e etc...
     
** Anotações 
   + A mudança de São Luís para o Pará foi a menor que já
     fizemos... Pouquinhas malas... Sem Kite, sem gato, sem prancha...
   + Foi, realmente, muito rápido. E daria, até, para ser mais rápido ainda
   + Na chegada a Belém de avião já dá para perceber algumas
     diferenças. De cima, vc já vê aqueles rios imensos!
   + A chuva é tão forte que a gente teve que ficar rodeando o
     aeroporto até ela dar um tempo e a gente conseguir parar
   + No Pará, eles chamam chup chup de CHOPP DE FRUTA
   + Estávamos em Belém em dia de REPA... Remo x Paysando... Remo fez
     3x0
   + Deu para ouvir os gritos, grande mobilização. Impressiona porque
     são 2 times da 3rd division Brasileira
   + Taperabá  = Cajá do Pará
   + Eles tem um sotaque chiado que lembra o sotaque que existe no Rio
     de Janeiro e o Português...
   + Assim que chegamos, fomos no Parque Mangal das
     Garças... Doideira, coruja viva, garças...
   + No Pará tem terminal HIDROVIÁRIO (sim, não é rodoviário). Eu
     nunca tinha visto. E tem muita gente que se locomove por meio de
     pequenas lanchas.
   + Dentro do rio, tipo lá no meio, tem um posto ipiranga! Sim, os
     barquinhos, lanchinhas, catamarãs, voadeiras, também precisam de
     gasolina no motor e param, no meio do RJ, para abastecer
   + Transporte em barquinhos é realmente uma parada em Belém
   + Não é por acaso que a Marinha brasileira tem uma grande base em
     Belém. Além do acesso ao mar, tem muito rio gigante relevante
     para adentrar no país.
   + Fomos almoçar no COMBU... Meio que uma ilha fluvial ao lado de
     Belém. Rolê muito doido. Uma mistura de churrasco na laje com
     vida/cultura ribeirinha. Aquela galera que mora ao lado do Rio e
     fica nadando. A água tem uma coloração barrenta. Mas, é
     quentinha. Funciona como uma espécie de praia também da população
     ribeirinha.
   + Quando chove muito, fica sem sinal. Como de costume, choveu por
     enquanto a gente estava almoçando no Combu. Tivemos que esperar a
     chuva passar para pagar! kkkk
   + As chuvas começam do nada e param do nada!
   + A mudança de são luís foi a primeira que a gente fez de
     avião. Chegou a rolar um avião em Dezembro e Janeiro. Mas,
     naquela ocasião, a gente saiu de fortaleza, deixou umas coisas
     lá, passou o final de ano em BH e, depois, voltou para Fortaleza
   + belém é feio com força, uma cidades mais feias que já vi. Até
     aqui, a mais feia que já morei. É pobre, velha, suja. O estádio
     do Remo e o do Paysandu são uma boa metonímia da misture de
     periferia, pobreza, fuleiragem e do componente pitoresco/exótico
     da cidade. O paysandu chegou as oitavas de final da libertadores
     em 2002/2003/?. Na época, chegou a ganhar do Boca Juniors dentro
     da Bombonera. Belém é isso. Doideira. Parece uma simulação.
   + Dá morrer embaixo de uma castenheira. Ela é a árvore responsável
     por gerar a famosa... Castanha do Pará!
   + Theatro da Paz.. Parada construída no século XIX, você entra e
     nem parece que você está em Belém. Parece Paris... Vários
     detalhes cruzam a história desse Teatro com a História do
     Brasil. Ele pega em cheio a transição do Império para a
     República... As referências ao imperador foram sendo apagadas. Um
     detalhe é que o Teatro foi uma construção dos barões do ciclo da
     borracha. Mas, depois de cem anos, o imóvel estava
     abandonado... O Estado acabou pegando e, agora, é uma parada
     pública.
   + Mercado de Ver o PESO, também chamado de "VEROPA" é o
     apelido... Cara, passei mal. Os standards de higiene são bem
     abaixo do que eu estava acostumado... Muitos urubus, cheiro de
     urina fudido, moradores de rua...
   + A estação das docas fica bem do lado, tem espaço com vários
     restaurantes oferecendo comida típica e tal... Mas, o nível de
     higiene é outro
   + Fomos na Casa do Saulo. Restaurante bem sinistro. Tipo Ribeirinho
     de luxo.Comemos um pastel com pato de tucupi e um peixe com
     banana assado que tava sinistro. O peixe é tão bom, mas tão bom,
     que às vezes nem lembra o sabor do peixe que você comeu em geral
     na vida. Os peixes mais comum, tipo a tilápia de supermercado,
     tem um certo gosto de ração de peixe, ou um ranço de peixe e não
     são suculentos. Esse peixe daqui é fofinho, cremosinho,
     suculento, cheio de água.
   + Estação das docas teve o raio gourmetizador na veia!
   + O Pará é TIPO *A ÍNDIA DO BRASIL*! Um monte de coisa exótica. A
     higiene não é lá das melhores. As paradas são muito sujas. Mas,
     tem uns bagulhos exóticos, diferentes, legais... Tem **muuuita**
     pobreza também.
   + Forte de Belém, fim de tarde, a maior concentração de urubus que
     eu já vi... Eles ficam pegando os restos do que rola no mercado
     do ver o peso. Tipo, A galera começa a descarregar peixe lá
     durante a madrugada. São muitos. Muitos mesmo.
   + Bom, não dá para falar de Belém sem falar de chuva haha. E a
     gente ainda foi na época que mais chove!
   + Na estação das docas a gente comeu uma lasanha de pato que tava
     uma sacanagem de gostosa...
   + Estação das docas é uma versão gourmet dos restaurantes que
     servem almoço do mercado do ver o peso
   + Fomos em dois parques dentro da cidade: Mangal das Garças e
     Parque estadual do Utinga!
   + O tecnobrega do Pará tem como característica um tecladinho safado!
 
** A SAGA da compra da passagem para ir de Belém para a Ilha de Marajó
De certa forma, comprar essa passagem foi Belém in a Nutshell 
+ foi um parto
+ não vende pela internet
+ vc chega e já tem Cambista
+ vendedora anota numa folha de papel pelo seu nome e sobrenome
+ se perder o papelzinho, pode se fuder 
+ pouca informação em sites
+ me lembrou daquele texto do DETRAN de Pernambuco 
+ viemos pessoalmente 
+ funcionários com mais de 70 anos + o que não é um problema em si. Mas eles parecem fazer o mesmo trabalho há 40 anos. Usando papelzinho
+ cada companhia vende trechos similares ou iguais. Tem um overlap. Por incrível que pareça, não tem uma tabela ajuntando tudo. + Também não tem uma forma fácil de saber se tem ou não vaga ainda disponível 
   
** Chuchup
   + Em Minas, chup chup
   + No Pará, chop de fruta
   + No Maranhão, cremosinho
   + No Ceará, ?
   + No Rio Grande do Norte, Din Din
   + Em Pernambuco, ?
   + Em Alagoas, Flau
   + No Piauí, ?
   + No RJ, sacolé

** comidas que provamos
   + tacacá da flávia
   + maniçoba
   + vatapá
   + peixe frito (piracuru) com açaí
   + sorvete de... castanha do pará
   + isca de peixe filhote
   + tucupi (gosminha embaixo do tacacá)
   + são pratos caros! Mesmo numa cidade barata, comendo street food,
     esses pratos eram tipo 20, 25...
   + Sorverte de UXI.. uma fruta da região que nunca tínhamos visto
   + Jambu... língua fica dormente... uma erva que é adicionada em
     vários pratos!
   + Lasanha de Pato da estação das docas tava abusrda!

** Viagem para Bragança
   + Futsal muito forte. Vários empresários colocam dinheiro para ver
     quem vai ganhar o torneio amador
   + Tem uma parte rica, nego anda de carrão e os caralho, em geral,
     quem tem embarcação..
   + Os caras tomam açaí PURO lá... Esse açaí que a gente come no
     sudeste, pro Paraense raiz, é "coisa de viado" kkk
   + Empachado = cheio de comida
   + Já desceu ali em Bragança embarcações com muitos produtos falsificados
   + Tem gente que come dois litros de açaí numa refeição! E ainda
     acompanha farinha, peixe, camarão... Charque às vezes...
   + Suco de açaí é uma parada que o paraense acha muito
     estranho. Seria tipo você falar para um mineiro tomar suco de
     vinagrete, pimentão ou tomate. Tem uma galera fit e riquinha que
     toma suco de tomate, mas, convenhamos, longe de ser a vibe do
     brasileiro médio.
   + Comida muito autoral, comemos um peixe com linguiça de porco
     sensacional, nunca tinha visto essa combinação
   + AJURUEMA -> faz referência ao nome da fruta. AJU é a fruta. Ruema
     é o local
   + Bacuriteua é a terra do Bacuri
   + Caratateua é a terra do Cará
   + Traquateua é a terra do Traqua, uma formiga
   + Tem muitas frutas e ervas diferenes específicas do Pará
   + ajurupeua… nome difícil, terra do ajupe 
   + cidade de Bragança feia 
   + praia de ajurupeua muito feia
   + táxi caríssimo + 100 conto só pra ir 
   + comida foda na CASA DO JAMBU
   + casas de ribeirinhos no caminho, vila de pescadores, brasil
     profundo, sinistro
   + uma das praias mais frias que já estive
   + do lado do mar tem floresta, não é arei, não é
   Pedra, não é matinho, é floresta mesmo!
   + ficamos caminhando e fazendo planos
   + perrengue pra chegar
   + nossa carona durou
   + viemos de ônibus 
   + centrinho da cidade, Porto de Bragança, muito frio, cheiro de
     peixe
   + da pra cortar o cabelo por dez reais 
   + muuuuitos urubus
   + pássaros que nunca tinha visto
   + árvores que nunca tinha visto
   + na frente do teatro da ps tem uma
   + não sei se anotei tudo do teatro da paz
   + vc entrar e parece que vc tá em Paris + e não em Belém
   + mercado de ver o peso quase vomitei
   + cheiro de urina fudido
   + muuuuitos urubus
   + eles passam a madrugada entregando peixes
   + óbvio que alguns peixes vão pro chão… os urubus ficam de olho
   + mesma coisa com Bragança, os urubus ficam ali de olho naquelas
     embarcações trazendo peixe da região
   + chegamos meio com perrengue, carona furou, ônibus, rodoviária,
     ônibus atrasou
   + muita chuva
   + almoço na casa do jambu, pesto pararnse… leva jambu… língua
     dormente
   + peixe com linguiça foi o prato proncipal
   + ficamos tentando ir pra praia, eu sonhando com surf, mas, sem
     surf rolando…
   + acabamos conversando com nativos e depois dando um rolê na cidade
   + a farinha é bem famosa… foram várias tentativas frutadas de
     comprar… famosa no estado inteiro
   + jantar top… pastéis diversos e a garçonete honesta sobre o
     camarão com nome da Chef que mora em NYC… prato principal foi
     outro peixe, com arroz de caranguejo…
   + acordamos, praia, esperança de surf, praia mais feia… tinha umas
     fezes humanas na areia… doideira… floresta bem do lado da praia

** Ajuruteua especificamente
   + Pará é a Índia do Brasil 
   + Tem que pagar pra pegar ônibus n rodoviária 
   + Concluso  ninguém paga aí ele fica parando e é pior pra tudo 
   + Coisas do subdesenvolvimento
   + Pra voltar da praia de ajuruteua pra Bragança é oralidade
   + Ônibus não tem hora varia de acordo com a lotação 
   + Os nativos dentro do ônibus não sabem direito
   + E é aquela coisa
   + Se achar ruim pagar oito reais e esperar um tempão num ônibus quente de um abril paraense
   + A outra opção é simplesmente pagar cem reais de táxi 


** Incursões exploratórias
   + Bragança
   + Ilha do Marajó
   + Salinópolis
    
