* 300 dias de vida nômade - Chapada dos Veadeiros

** Notas
 - comemoramos na chapada dos veadeiros
 - lugar que é um hub de gente esotérica e místicos
 - 300 dias nômade
 - linda
 - lembra serra do cipó 
 - hub de vegano, vegetariano, canabistro
 - água fria
 - cerradão 
 - vale da lua… nome muito bom… não sei porque teve aquela formação… mistério

 Vida nômade - estou realizando o sonho de geografia… sem ter feito o
 curso

 A gente vira: climatologo, oceanógrafo, geógrafo, cultural expert,
 linguistas… como diz o cara no livro!
 - Vi uns caras no Aeroporto com roupa do projeto RONDON... Projeto
   rondom - não fiz na faculdade, mas morei em Manaus, Belém, Alter do
   Chão
 - mistura de Maconheiro, Hippie, histórias de disco voador e ET...
   Toda hora
 - tinha um lugar chamado CANNABISTRÔ! Fala sério...
 - paisagem muito bonita
 - lembra serra do cipó
 - esse ano já foi chapada das mesas (MA/TO), agora Chapada dos
   Veadeiros (GO)... Ainda falta umas 5 Brasil afora....

 - os apartamentos que a gente fica não são nossas casas... não são
   customizados... isso é meio foda...
 - a gente NÃO tinha água filtrada pronta em VÁRIOS lugares... São
   Luís, a gente enchia garrafas na academia. Em Manaus, a gente ia na
   Academia do Hotel, já que a gente morava numa academia dentro de um
   hotel. Em Belém, a gente pedia para as funcionárias da cozinha do
   Hotel. Em Alter do Chão, a gente até tinha um filtro... Mas,
   duvidando da qualidade da água, a gente tinha que comprar água. Em
   Jeri, a gente comprava o butijão/galão de água. Em Canoa Quebrada,
   não lembro... Em Pipa, também não lembro. Acho que a gente comprava
   água em plástico. Em João Pessoa, tinha um filtro meia bomba... Em
   Itamaracá, era galão e os ingleses trocavam. Fortaleza, também era
   galão.
