* Day 1: a mudança

  Essas anotações vem de arquivos em mark down

**  Anotações aleatórias do arquivo "terra brasilis"
   ### Day 1

   - É começou 
   - 4 semanas vacinados
   - click do nada
   - em 12 dias, fizemos a mudança
   - sorte com a proprietária
   - decisão do destino
   - pintura, foto da misty
   - estressante, rinite, vendemos tudo
   - gastamos cerca de 15 mil
   - levantamos 11 mil
   - Fernanda é CEO, COO & CFO.  E eu? Bom, eu só o imagineer, uma
     mistura de imagination and engineer :) (apesar de não ser formado em
     Engenharia)

**     Anotações aleatórias do 'Day 1 mudança' (markdown)
  # Dia 1: A mudança



Depois do dia 0 e do dia i, finalmente, chegamos no primeiro dia da
jornada, aquele que pessoas normais usariam num diário de viagem. E
nele ocorreu a nossa primeira mudança, o rompimento com o cordão
umbilical de uma moradia fixa!

Desde já, é bom esclarecer que o dia 1 não é só um único dia. Calma,
ainda não virei a Dilma.

A data de 28 de Agosto de 2020 é, acima de tudo, simbólica. Nós
fizemos a mudança de fato com caixas, carreto e gato caindo para fora
do caminhão, saindo do Recife para a Ilha de Itamaracá em um único
dia, que marca o início de nossa jornada. No entanto, os atos
preparatórios e os atos de execução da mudança com certeza
transcenderam esse pequeno intervalo de 24 horas.

Entre o momento em que decidimos mudar e a mudança de fato foram 9
intensos dias. Muito rápido para qualquer cidadão normal. Não era pra
ter sido tão rápido. Simplesmente, aconteceu.

Inesperadamente, os astros convergiram para isso. Nossa gentil
proprietária tinha interesse que nós saíssemos rapidamente do
apartamento, já que o filho dela procurava por uma nova moradia.

Assim, vendemos quase tudo, empacotamos o que sobrou de essencial e
preparamos a entrega do apartamento em 9 dias. Insano.  Muita gente
não prepara nem o imposto de renda do 0% ao 100% num prazo de dias,
mas missão dada é missão cumprida!

### Saldão e desapego

Escrevo este texto quase dois meses depois da mudança e posso dizer
que, até agora, essa primeira mudança foi um dos momentos mais
desgastantes da vida nômade. Dezoito meses antes, nós havíamos entrado
em um apartamento sem mobília. Acabamos mobiliando no sufoco, já que a
entrada coincidiu com a eclosão da pandemia no Brasil, veja o texto
sobre o dia 0 da jornada, no Recife.

Dezoito meses depois, eu me considerava uma pessoa com inclinações
minimalistas. Lembrava de ter comprado pouquíssimos objetos durante a
pandemia. E de fato devo estar muito abaixo da média. Mesmo assim, na
hora do "vamo vê", é impressionante! Os cacarecos se multiplicam como
gremlins.

Além das paradas inúteis ou semi-inúteis, existiam os objetos úteis!
Infelizmente, é inviável ter uma vida nômade com fogão, geladeira,
microondas, cama, mesas, sofá, TV de 40'', cadeira de trabalho... Pera
aí, cadeira não! Essa daí, até agora, foi bravamente mantida! :)

Todo o resto mencionado e outras paradas, acabaram tendo que sumir. E
por que não fazer um dinheirinho para desapegar?

Foi isso o que fizemos. Gastamos cerca de R$ 15.000 para mobiliar o
apartamento. Incrivelmente, conseguimos faturar com as vendas cerca de
R$ 11 mil. Quando decidimos que iríamos vender, eu estaria feliz de
ter de volta 33% do que gastei.

Alguns fatores contribuíram para isso. Primeiro, o empenho da CEO (e
CFO do casal). Baita vendedora! Desovar nosssas propriedades virou um
demandante *side-job*. Até um instagram específico foi
criado. Segundo, a nossa localização era estratégica. A gente morava
num condomínio de 3 torres, sendo que cada torre tinha 32 andares com
6 a 8 apartamentos. Muitas cidadezinhas no interior de MG não batem
isso aí!

\### 4 malas, 7 caixas e 2 gatos

\### Uma nova casa
