* São Luís, Março de 2022

** Barreirinhas - Apetitizer
   + saindo de jeri, fomos para Barreirinhas passar o carnaval conhecendo os lençóis maranhenses
   + já dá para sentir umas diferenças, acho que, até aqui, o Maranhão
     parece ser a região realmente mais pobre que já vivi
   + existem áreas precárias e pobres em todas as cidades grandes que
     eu já morei: BH, Rio, Recife, Fortaleza...
   + Maranhão parece difernte - até que ponto isso não é preconceito também?
   + umas paradas muito virgem
   + essa parte do Brasil, de Jericoacara para esquerda, é um Brasil
     que pouca gente conhece...
   + MAranhão é nordeste, mas tem hora que tem clima de NORTE! Veja
     barreirinhas e o clima com o Rio...
   + fun fact: eles chamam LANCHA de VOADEIRO
   + fun fact: no Maranhão, AÇAÍ é chamado de JUSSARA... o que é
     engraçado, parece nome de secretária...
   + O trecho de BARREIRINHAS até ATINS é o primeiro trecho que eu,
     como usuário do Google Maps, não consegui visualizar como seria,
     quanto tempo demoraria e etc. Fazendo a parada, acabei
     descobrindo que era perrengue para cacete! Tem que usar 4x4,
     balsa, areia fofa, rio no meio do caminho... Dá para ir de lancha
     também!
   + a vegetação nas dunas dos lençóis é de CERRADO e CAATINGA. Perto
     do Rio, ele vai mudando conforme o tempo vai passando, mas tem
     uma hora que fica MATA DE COCAIS.
   + Rally dos ventos - parada muito sinistra que rola nos lençóis.
    
    
** São Luís
  + Achei que não ia ter surf, chego na cidade: carro com long. Mas,
    poderia ser alguém viajando para o Ceará, por exemplo. Daí a
    pouco, vi um surfista na praia andando com uma prancha e um pico.
  + Achei que não ia ter surf. Já tinha até aceitado essa "verdade".
  + Vai ter surf sim!
  + Arroz de Cuxá - prato típico - um arroz com uma erva e um
    camarãozinho seco
  + Os locais chamam São Luís de "A ILHA"... E é mesmo uma ilha... Uma
    "ilha" quase conectada de forma imperceptível ao continente. Tem
    um rio cortando uma parte.
  + a gente meio que tá fazendo a ROTA DAS EMOÇÕES nos últimos 2
    meses: Jericoacoara, Barra Grande, Delta do Parnaíba, Atins, Santo
    Amaro, Lençóis Maranhenses e muito mais.
  + CF98 - clima de praia, beach volley, beach tennis, seguro, infra
    top e com excelente custo benefício
  + conhecemos o Sérgio, formou na EBAPE emm 1971... Lenda, teve aula
    com o Mario Henrique Simonsen
  + Gafanhoto - restaurante vegetariano TOP
