* Jericoacara, Fevereiro de 2022

** Pensamentos
   - vibe de pipa parecida
   - cidade de areia! podia ter lido DUNE
   - muita hype
   - mulheres ultra bem vestidas, maquiagem e roupas chics
   - muitos gringos
   - onda fraca, mas uma merreca que dá para divertir
   - serviços interessantes
   - vento forte no preá!
   - muito PEGA BOBO! Bizarro, bugre queria cobrar 300 reais
   - galera explora muito
   - reserva de mercado no transporte dentro da cidade
   - por do sol absurdo e muito raro no Brasil pela geografia
   - existem alternativas -> jerilícia - almoço de R$ 14
   - ficamos sem ar condicionado pela primeira vez, foda -> muito mais difícil de trabalhar no calor
   - sem os gatos, assim como em fortaleza
   - acesso muito difícil, só vai rico. Aeroporto + carro. Longe de
     grandes centros
   - não vi ninguém famoso, rs. Mas, provavelmente, tinha alguém lá!
   - acordar, dar uma caminhadinha, voltar para casa. Pouco surf. Pouco kite.
   - acidente foda de kite, prejuízo de 700 reais...
   - consegui umas caronas para ir e para voltar do preá... O risco
     era continuar numa caminhada de 3 horas
   - Rancho do Kite: coisa top. comida top. vibe sinistra.
   - prime gourmet compensava demais
   - praia central um pouco suja, crowded, cheia de alga, um amigo nem
     curtiu... Depois, deu uma melhorada
   - muito gato de rua...
   - diferente de pipa, são váaarias ruazinhas, tem muitos becos
   - local realmente LOCAL é difícil de achar em Jeri, maioria da galera de fora
   - excursões não foi e nem vai ser tão fácil como em Pipa, Cabedelo,
     Fortaleza ou Canoa Quebrada. Não chegamos de carro. Não era fácil
     de alugar carro.
   - Achei Jeri maneiro. Mas, pro hype que existe, não é isso tudo. Se
     eu fosse solteiro, rico, curtisse balada, talvez, a opinião fosse
     outra. Entre passar mais 1 mês em Fortaleza, Paracuru, Iguape ou
     Jeri - eu escolhia todos os outros 3 no lugar de Jeri. Fácil!
     Mas, talvez eu seja uma _surf bitch_! haha
     
   - Sem dignidade em Jericoacara
   - bugueiro querendo cobrar 300 reais para levar a gente pro preá
   - um outro cara queria coobrar 120 reais
   - eu consegui de graça pedindo carona
   - outro dia, 
   - impressionante, cruza a fronteira do Ceará com o Piauí, e já tem diferenças
   - mata de cocais
   - Bacurí! Uma fruta usada pra fazer sorvete
   - moramos em Jeri, saímos na sexta de carnaval... história para
     contar. Vi, vivi e sorri em Jeri.
   - Na próxima, acho que eu ficaria no Preá. E tentaria ter um carro
     4x4 alugado. Faria muita diferença na região. Preá mais barato
     que ficar na vila de Jeri.
          
** Sem dignidade em Jericoacara
   - acordar 4am
   - aquele leve enjoo
   - uma leve vontade de ir ao banheiro
   - estava normal no dia anterior
   - chega lá, temos cerca de 1 hora de aula de história sobre
     canoagem
   - aprendemos que as árvores tem sentimentos e devem ser perguntadas
     sobre se querem ou não ser uma canoa
   - ponto engraçado de religião, as pessoas fazem piadas e acham
     ridículas outras religiões. No Brasil, parece especialmente comum
     a cara de nojinho e de estranhamento em relação ao islamismos (ou
     aos muçulmanos). Isso é tão forte que a expressão "chuta que é
     macumba" é um ditado popular
   - Ao mesmo tempo, se alguém comprar um pão numa padaria, comer,
     achar ruim, cuspir e disser "chuta que é hóstia"... isso termina
     em briga
   - leve vontade de ir ao banheiro antes
   - me caguei todo
   - saltar do barco e terminar nadando
   - fernanda pistola pq perdi a paciência
   - custou a bagatela de 135 reais
   - eu era o pior remador
   - mal deu para apreciar a vista
   - barragem de Mariana
   - quando eu achei que tinha acabado, na caminhadinha, acabou tudo
   - minha sunga virou uma fralda
   - fiquei nu e me limpei na praia
   - um dos piores momentos da minha vida
   - as mulheres limpando a canoa no final
   - cheguei lá e elas me perguntaram se eu tinha vomitado... ou seja, ninguém percebeu!!!!
   - um milagre no meio de tanta merda!!
   - essa história aconteceu com um amigo de um meu...
   - os fatos narrados vão ser narrados na primeira pessoa única e
     exlusivamente para criar uma proximidade com o leitor
   - os fatos são baseados na realidade... mas, não necessariamente
     totalmente vinculados a ela
   - lugar do glamour
   - as instrutoras disseram que em 4 anos, isso nunca tinha acontecido, de alguém pular kkkk
   - eu perguntei se podia. horas depois, eu descobri que a instrutora
     disse não. mas, eu posso jurar de pé junto que eu ouvi um sim kkk
   - grande lição, mesmo que vc esteja suando frio e quase se cagando
     numa canoa com outras 4 mulhres, não seja rude com a sua
     esposa...
   - dado que isso começou de madrugada, o perdão e as explicações
     completas sobre o que se passou ali demoraram cerca de 12 horas...
   - discussão, fernanda me dá a CHAVE de casa na minha mão
     cagada... Não... Na mão cagada???
   - justo a sunga novinha... que ganhei da minha sofra no último Natal...
   - não cheguei no carnaval ainda e a sunga já tá breada...
   - a PedrA é Furada... Já o PedrO...
   - o cara disse que bater na canoa deveria vir acompanhado de um pedido de desculpas
   - e CAGAR? e PEIDAR FODA?
   - será que eu vou pro inferno dos canoeiros? com diabinhos batendo
     com remos de madeira na minha bunda ossuda para o resto da
     eternidade? Diferente do Hulk, não tenho nem uma carninha para
     dar uma amortecida
   - quando eu vi a última curva... quando vc chega perto de
     casa... não tinha mais forças... minhas pregas cederam... e por
     um leve instante de tempo, o universo parou, as coisas
     aconteceram em slow motion e eu me peidei. Um peido de liberdade!
   - o único problema é que o peido veio PREMIADO... OU melhor, CAGADO...
   - nesse momento, como ensinado por Napoleão Bonaparte, situações
     críticas merecem decisões críticas. Perguntei à líder (tem um nome para essa pessoa que fica)
   - aftermatch... a argentina da canoa trabalha na madrugada no
     passeio de canoagem e no início da manhã, já engata em outro
     trampo... alugando prancha de surf... justamente o cara que eu já
     tinha acerta 30 conto a hora num loong... O que vc acha? Fui
     nesse fornecedor ou procurei outro e tive que pagar caro?
   - Aftermatch -> nessa época, estávamos dividindo um apartamento com
     um casal de amigos... O cara quase foi no passeio... desistiu pq
     tinha estado os últimos dias com diarréia e dor na barriga... Já imaginou se ele tivesse ido?
   - quando eu saí da água, tinha corrente, tava longe, a disposição física não era mesma
   - esposa continuo na canoa, as pessoas perplexas:
   - ele sabe nadar? sim
   - mas, sabe nadar bem? porque tem corrente, pedra e tá uns 300 metros da areia
   - quando a sunga virou uma fraulda, vc poderia pensar: o que é um peido para quem já tá cagado?
     bom. Se ficar só no peido. Procede. O problema é o que vem depois.
     Naquele dia, o peido era o prenúncio do desastre.
   - o que rolava comigo era tipo contração de grávida. Ou de série de onda em alguns praias.
     eu consiga dar uma segurada, mas, de tempos em tempos, voltava a pressão e eu tinha que segurar o rojão
   - sim, sabe - disse ela.
   - aftermatch da esposa: pqp, se esse arrombado morrer nadando eu mato ele. 
   - aftermatch da argentina: hijo de puta. já ha passado toto el
     passeo sen fazer un piu de forza, tutto hai ficatto para mi. E
     ahora, se questo puto morre, yo estoy fudida con me patron.
   - aftermatch da cearense local: cabá da peste e atrivido. se fosse
     macho mermo aguenta 1 horinha de canoagem. Deve ter crescido em apartamento esse fi de rapariga.
   - aftermatch meu: rapaz, essa história vai ficar maneira no blog kkkk
   - aftermatch do dono do passeio: (foram tiradas) esse é o cara que
     pulou né? Putz, olha a cara do maluco. O cara tá verde. Tá suado
     igual uma tampa de marmita.
   - final feliz: achei que eu ia encontrar a galera e ir
     embora. Sempre pode piorar. Depois da aula das canoas, de sofrer
     em cima das canoas, de cagar na canoa... Tinha que guardar e
     conversar sobre tudo que rolou...
   - Mais: a mulher pistola comigo
  

** Excursões exploratórias
  - rancho do kite no preá, muito top
  - preá
  - lagoa do paraíso
  - aqueles 2 clubes: o que dava para pular e o que tinha a tiro-lesa
  - Barra Grande - a nova jeri?
  - Praia do ARROMBADO - não tenho maturidade...
    - vi 1 surfista
    - comecei a conversar com o amigo do cara
    - ele tinha duas pranchas
    - entrei no mar para ver se ele alugava
    - o cara falou que não alugava... só emprestava!
    - Piauíense da PORRA!
    - um anjo... emprestou para mim e para minha esposa
  - ilha do guajiru - absurdo! Muito bonito, mesmo! ASsim como Icaraí de Amontada
  - parada muito virgem
  - muito investimento rolando
  - aqueles cantos do Brasil... que tem mais estrangeiro do que
    Brasileiro... Turismo high end
  - assimetria de Barra Grande. 2 serviços 1 ultra high end, caríssimo
    para região e sem competição. As outras paradas meio que frequentadas por locais
  - difícil de chegar no litoral do piauí... aeroporto de Jeri, ou
    aeroporto de fortaleza (mais longe ainda), ou aeroporto de
    Teresina! Que é longe para caramba do Litoral.  Por que não
    fizeram Teresina de capital? Talvez porque a capital tá muito
    centralizada, perto do Maranhão, Tocantis, Pernambuco, Bahia, Ceará...
 
