* Day 316: Praia do Francês

** Road-trip até chegar aqui
   - sinistro, saindo
   - Estrada - só caminhões perto de salinas
   - fetiche de caminhoneiro com CHURRASCO
   - preço inacreditável - 20 reais rodízio - como?
   - Norte de minas - salinas bem pobre
   - nascer e se por do sol é muito bonito em minas no inverno. Zero nuvens 
   - Vitória da Conquista, BA, bem central o hub: Hub bem central do
     brasil
   - 
     
** Canyon do São Francisco, Canindé, Sergipe
   - Fato curioso... grandes intervenções do homem na natureza, em
     geral, atrapalham passeios de turismo na natureza...
     Curiosamente, a Usina Hidroelétri do Xingó foi o oposto... Ela
     criou eco-turismo! alargou o rio
   - Tem umas piscinhas cercadas por grade para nadar. Isso por conta
     das piranhas...
   - 
     
** Notes
   - duas vezes em maceió, meio de 2017 e meio de 2022. Chuta quando
     teve as maiores chuvas?
   - Marcondes Rocha -> história de um cara que foi herói local,
     prodígio do surfe (ganhou em 3 categorias no mesmo dia), campeão
     de tudo no amador, e que hoje parece viver em completa
     decadência. Alguns vídeos: [[https://www.youtube.com/watch?v=4uXjuVLGl8M][1]] [[https://www.youtube.com/watch?v=BPUPtWl6YaE][2]] [[https://www.youtube.com/watch?v=4tSm3Mnovws][3]] [[https://www.youtube.com/watch?v=niX52gAca2A][4]].
   - Dou um azar foda com a região de maceió, vim 2 vezes... as duas
     com chuva foda e ficando doente.
   - Ia ter WQS, mas foi cancelado
   - 


