* Alter do Chão, último terço de Abril

** Hard Facts
   + DDD de Alter do Chão é 93
     
** Anotações aleatórias
   + Breu branco -> produto da Amazônia usado pela Natura
   + formiga que, quando morta, gera um repelente natural, muito
     maneiro!

** Chegada
  + Cara, somos muito animados Sexta, q maior missão pra fazer duas horas
    de surf enfrentamos 9 horas de ônibus Já acordamos no sábado, saimos
    do hotel dez e quarenta, pra chegar na próxima hospedagem de carro
    avião as 3 da tarde Puxado A gente é muito animado Meio desidratado,
    com fome, cansado, mas vamos levando
  + Alter do chão tem tipo uma orla Meio doideira Eu vi uma mulher de
    biquíni passeando com um cachorro No Rj, seria normal, na orla da
    cidade Aqui é engraçado Pq vc tá no meio da floresta. Além disso, a
    moça tinha traços indígenas como a grande maioria dos nativos. Quando
    vc pensa em índios no meio da floresta, vc não os imagina andando de
    biquíni, com fone de ouvido e um labrador de pedigree haha. Não é a
    imagem que eu esperava. Sem problema nenhum
  + Aqui, chegamos pela primeira vez de BARCO em casa! Hahaha Essa foi
    foda. Pegamos uma carona com um motorista de lancha. Ele para na rua,
    vc desce no asfalto em meio a folhas molhadas pelo rio, vai pra casa
    volta e entra de novo. É outro tipo de mobilidade
  + Os peixes que vc come aqui são sacanagens. Nem parece peixe. É outra
    parada. Muito suave
  + Ontem, o episódio do jacaré. Vc tá voltando de uma trilha. Quando vc
    escuta as pessoas urrando, comemorando, uns nativos conseguiram
    capturar um jacaré e estavam levando ele pro IBAMA. Doideira. Estamos
    voltando do PICO DO PIRAOCA. Sim, aquele A ali no meio salvou. Se não,
    seria PICO DO PIROCA.
  + Supermercado caríssimo em alter do chão. Um yogurt foi 4.5.
  + Mata FECHADONA. Chegando em Santarém vc já vê.
  + São duas cidades alter do chão. Uma na cheia e outra na seca. Foto da
    ilha do amor quando fomos. Foto da internet de como é na seca.

** Anotações aleatórias
  + Alter do chão - todo mundo com cara de índio, comida de índio,
    natureza, Amazônia… e o nome da cidade é de índio? Não! Um nome
    que vem de PORTUGAL HAHAH
  + Como chama o serviço de Táxi de Aler? BOTOCAR, sim, de boto!
  + Na região de Alter, além dos TAPAJÓS, que parecem ter sido o
    grande povo indígena da região dando nome ao rio, especificamente
    em Alter ficam os BORARIS!
  + Tem enguia elétrica nas águas do Tapajós, inclusive, enguia de
    mais de 3 metros de comprimento!
  + Em alter do chão tem tipo uns HIPPIE VELHO, magrelo.... Tem hora
    que parece búzios da Amazônia
  + 

** Nosso estilo bandeirante
  + A gente viaja estilo bandeirante, mais continuo, indo de faixas
    do território pra outras faixas. Boa parte foi de carro. Isso faz
    com que vc veja as mudanças de forma contínua

** Passeio na FLONA
   + árvore gigante, sibaúma
   + formiga que, quando morta, vira inseticida e libera um cheiro de
     mentol!
   + Canal do JARI -> passeio para ver animais, indígena coloca a mão
     no formigueiro pro cara que quer casar com a moça. Se ele quiser
     mesmo, tem que manter a mão lá por um tempão
   + 

** Alguns termos indígenas

   - Igapó- floresta alagada
   - Jará - frutinha vermelha 
   - Pracutá - árvore 
   - Bacuri - fruta amarguinha, gostosa demais!
   - Mijacão (frieira) -> pingar a vela    
