* Day 30: Ilha de Itamaracá

Foda cara...
Eu meio que perdi o arquivo... Tinha feito uma cacetada de anotaçoes...
Tem em algum caderno meu de anotações

* Anotações aleatórias
  + DDD 81, ainda no Recife
 
  + 

** Isso aqui veio do arquivo "terra brasilis" (um org mode)
   ### Itamaracá: raiz
       - seção de fun facts -> 3 instituições prisionais: 2 presídios e 1 manicômio judicial
       - seção de SINCERICÍDIO -> cidade suja e feia. Mas, o vento é top e o mar é flat. Além de ser perto do Recife.
       - número de opções de peixes > número de dentes na arcada dentária per capita
       - mobilidade urbana -> combi
       - pousada dos ingles
       - foto da workspace station
       - o que vivemos agora, não parece possível de ser vivido 10 anos atrás no Brasil, faltaria internet, a não ser em capitais. Menor liquidez de pousadas e etc
       - Olhando para a minha vida pessoal, seria impossível  viver isso até o fim de 2019. Em 2020, seria possível, mas não recomendado com o início da pandemia
       - Talvz, não seja até hoje. Whatever.
       - Leitões caminhando na rua
       - caranguejo vivos
       - tamanho do camarão
       - condições de higiene precárias, devo admitir. Mas, aquela comida que vc come em barraca de praia usa o mesmo fornecedor, meu amigo, rsrs.
       - Dois caras com camisas do cruzeiro. Foda. Esses caras me perseguem. Morei no RJ 6.5 anos. Durante 1 ano, em frente ao encontro da torcida no RJ. Tem base?
       - Uma placa sobre AMADO BATISTA -> "compre uma casa e ganha uma mulher feliz"
       - Vida Rural -> cavalos pastando
       - música do Dorival Caymi, sugestão do Bruno Cuconato. Voltar...
       - tem também a do reginaldo rossi, que começa com uma imprecisão, rsrs
