* 1 ano de vida nômade

- caramba, 1 ano
- passou rápido
- ao mesmo tempo que vivemos muito, foi pouco tempo
- e falta ainda mais lugares para se conhecer...
- uma parada, a gente gastou 1 ano, basicamente, com o Norte e o
  Nordeste do Brasil... Parece pouco. No entanto, são as duas maiores
  regiões do Brasil!
- além disso, o Brasil tem uma posição específica:

  1. Russia — 17,098,250 km²
  2. Canada — 9,879,750 km²
  3. China — 9,600,013 km²
  4. United States — 9,525,067 - 9,831,510 km²
  5. Brazil — 8,515,770 km²
  6. Australia — 7,741,220 km²
  7. India — 3,287,260 km²
  8. Argentina — 2,780,400 km²
  9. Kazakhstan — 2,724,902 km²
  10. Algeria — 2,381,741 km²
  
  É o quinto maior país do mundo... Mas, Canadá e Rússia são os dois
  maiores.. Só que boa parte do Canadá e da Rússia não são habitáveis
  ou são muito hóstis. A China, além de muito hostil culturalmente, é
  uma ditadura e está com a situação do COVID

  Acaba que o país, entre os países gigantes, talvez seja o melhor
  para fazer vida nômade. É muito grande. É barato. A gente é daqui.
  Todo o território é amigável em termos de clima.
