* Day 270: Manaus

** Hard facts:
   - DDD de Manaus é 92
   -

** Anotações aleatórias
   - ESTAMOS EM MANAUS: Venezuelano pedindo esmola. Daí a pouco, um
     Venezuela insistindo em usar o banheiro. Seguranças foram
     chamados
   - Todos os garçons são Venezuelanos naquela praçinha que fica ao
     redor do Teatro de Manaus!
   - 2022 e ROCK está na moda em Manaus! Acho, inclusive, que vai ter
     show do KISS, vi uma galera com camisa (na real, eles são daqui e
     estavam indo a shows em outras cidades - o que mostra o
     fanatismo). Os bares tocam rock. Os motoristas de Uber tocavam
     Heavy Metal (metálica). Onde rola isso? Are we still in the magic
     80s?
   - Conhecemos a Diana, uma farmacêutica que nasceu em uma aldeia
     indígena próxima a santarem. Com 10 anos, saiu da aldeia pra
     Santarém. Minha idade, eu sou 1993; ela 92. Infâncias totalmente
     diferentes. O irmão anda nu. Ela até hoje fica sem a parte
     superior quando dentro da aldeia.
   - Blog - Manaus - dá pra ir pra Roraima de ônibus, todos os garçons
     são venezuelanos, Manaus é DUBAI da Amazônia, aquele restaurante
     do almoço foi sinistro, pqp. Costela de tambaqui. Cabroquinho tem
     um sanduíche típico foda, com uma fruta no meio (tucumã!)
   - 

** Buy, hold, or sell?
   - Buy - pessoal de fora do Norte não tem noção do que é Manaus!

** Teatro Manaus
   - Nos pagamos 20 reais pra ver o show de uns lugares mais baratos
   - Esse espetáculo é subsidiado
   - baratinho pra ver pouquinho
   - mas, menos de 200 anos atrás, em meados do século XIX, pessoal
     pagava muuuuito caro pra ter isso aqui
   - vc vê como as coisas avançaram e melhoraram
   - era muito inacessível
   - escravos sequer poderiam entrar
   - hoje, qualquer pessoa com um celular consegue assistir
     infinitamente as melhores óperas do mundo
   - mesmo tendo essa possibilidade, o que pesso assiste? Dancinha de
     tiktok, pornografia e futebol. Stuart Mill estava certo. Povao
     entregue aos prazeres de um porco epicurista.
   - na foto da pra ver que nesse lugar vc não vê quase nada do palco,
     ele estar atrás da mulher volupuosa à minha frente
   - foi minha primeira vez assistindo uma ópera, bem impressionante!
 
**     



