* Probably Asked Questions (PAQ)

** Como ficava o fluxo de caixa?

Algumas vezes, era bem estrangulado. Em Outubro de 2021, por exemplo,
pagamos 50% do custo de moradia de Novembro, Dezembro, Janeiro e
Fevereiro!

Isso porque fechamos com antecedência. Era importante fechar com
antecedência a moradia porque são meses próximo do Verão ou dentro do
Verão, uma estação mais procurada por turistas.

A prática desse mercado de hospedagem é diferente do aluguel
convencional de moradia fixa. A gente fechava 50% do valor total
ao concluir a negociação e 50% de pagamento ao ingressar no imóvel. Às
vezes a diferença entre esses dois momentos era de muitos meses!

** Atrapalha a produtividade?
Sim. Se a pessoa for de fato workholic, essa é vida é
inconciliável. Poucas pessoas de fato trabalho absurdamente.

** Fica muito caro levar essa vida?
Menos do que as pessoas imaginam. Cada texto de cada lugar tem uma
seção /Money talk$ bull$hit walk$/

** Dá para curtir tendo que trabalhar?
Menos que de férias. Mas, mais do que morando no mesmo lugar de forma
acomodada.

** Pets?
Temos gato, não cachorro. Dificulta. Mas, dá para fazer. Cachorros
costumam ser mais homogêneos que gatos. No caso de gatos, é preciso
ver como cada um reage a essa vida. Talvez, eles fossem mais felizes
vivendo sempre no mesmo território e sem viver uma mudança por mês.
