* Lugares para surfar por estado

De certa forma, estou cumprindo a missão dos cara da Surfari! Olha o
quanto eles precisaram reivindicar para viver o que eu tenho vivido
com a minha esposa, melhor amiga e musa!

Curioso que os caras do Surfari iam (inicialmente) do Rio Grande do
Sul ao Ceará!  A viagem do Surfari durou 4/5 meses. A nossa acho que
vai durar uns 14 meses.. só para pegar Brasil

** Pernambuco

** Sergipe

** Bahia

   Veja o portal Surf Bahia. Surfaria enfatizou (Barra Grande, Morro
   de São Paulo, Salvador)
   
*** Norte da Bahia
   - Praia do Forte
   - Salvador
   
*** Centro da Bahia   
   - Barra Grande (Muraú - onda para caramba!)
   - Morro de São Paulo
   - Ilhéus (onda cheinha, longa, mais fácil)
   - Itacaré (tem um clube de longboard)
     - Tiririca
     - Engenhoca
     - Havaizinho

*** Sul da Bahia     
   - Praia do Norte
   - Olivença (Praia de Backdoor de Olivença)
   - Trancoso
   - Abrolhos


** ES
   - Regência! Indonésia por 30 reais...
     
** RJ
   - Saquarema e Recreio, são os lugares!
     
** SP

*** Norte de Sp (melhor)
    Swell de Sul e de Sudeste... onda para todo mundo!
    Surf expande a alma
    O mundo seria melhor se mais pessoas surfassem
    Oscar Niemeyer "tem que tentar não ter uma vida merda!"
    "tudo que eu faço é surf"
    "longarina" é long bailarina - lá em Maresias
    surf é a minha meditação (meditar mesmo é muito difícil)
    - Ubatuba e Maresias (Paúba, praia perigosa)
    - Ubatuba é uma das mais constantes de todas
      
***   Centro e Sul de SP
   As melhores praias de surf são Santos e Guarujá Surf é o novo golf,
   entre os ricos e esportistas! (acho que kite é mais) Surf tem
   muitas semelhanças com empreendedorismo. Santos primeira cidade a
   ter surf no Brasil!
   - Guarujá e Santos são as melhores do Centro e Sul do Estado de SP
   - Maresias e Ubatuba são as principais do litoral Norte
   
** PR
   - Matinhos -> a onda mais longa do Brasil, 50 segundos de onda
     
** SC

   Norte de SC tem uma sombra de swell gerada por Floripa
   Minha prancha é o meu tapete voador!!
   Balneário Camboriú bem no Norte
   
*** Florianópolis
   Swell de leste! Surf é foda... Tem uma magia...
   
   - Jurerê
   - Ingleses
   - Brava
   - Santinho
   - Moçambique
   - Barra da lagoa
   - *Joaquina* 
   - Campeche
   - Matadeiro
   - Lagoinha do Leste
   - Naufragados



** Rio Grande do Sul 
  - Barra do Chuí
   
