#+TITLE: Professor Joaquim Falcão
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil

#+begin_export html
<p class="subtitle">23 de Fevereiro de 2018</p>
#+end_export

Boa noite a todos, @@html:<span class="marginnote">Este discurso foi proferido como uma homenagem ao professor Joaquim Falcão na cerimônia de colação de grau da turma de 2013 da FGV DIREITO RIO. Neste dia, a versão falada foi próxima, mas não idêntica a este texto. Com o objetivo de tornar o discurso mais próximo de uma fala e não de um texto escrito, o tom é propositalmente informal. Assim, algumas conjunções cabíveis foram omitidas.</span>@@

Fazer um discurso para o professor Joaquim é uma honra muito grande. Eu me sinto muito feliz de vir aqui e poder bater esse pênalti.

Por obra do acaso, os últimos 5 anos do professor Joaquim como Diretor coincidiram com os 5 anos dessa turma na FGV. A nossa turma não podia deixar essa coincidência passar batida.

Hoje é um dia simbólico. Esta noite representa o encerramento do ciclo do Professor Joaquim como Diretor e o começo do nosso ciclo como profissionais formados.

Assim, vou destacar quatro virtudes do professor. Isso tem duas funções. Primeiro, fazer um elogio. Segundo, usar essas virtudes como fonte de inspiração para todos nós, formandos.

** Juventude

A primeira virtude que eu gostaria de falar é juventude. Talvez alguém esteja falando: "uai, mas o Joaquim é aquele senhor ali, baixinho, de cabelo branco e o cara vai falar de juventude?". Isso mesmo, juventude. Vou falar sobretudo de juventude de alma.

Vocês já observaram uma criança de colo, um bebê? Já notaram a curiosidade com que ele olha o que tem ao redor? Já perceberam a abertura com o que é novo e diferente?

É assim que o professor olha o mundo, com abertura e com flexibilidade. Essa postura diante da vida te ajuda a ser vanguardista, te ajuda a inovar e te ajuda a fazer coisas diferentes.

** Humildade

A segunda virtude que eu gostaria de falar é humildade. Como o professor gosta muito de contar histórias, eu vou contar um "causo".

Uma vez o professor convidou um aluno, do quinto período, para dar aulas com ele em uma disciplina. Não foi para ser monitor. Foi para ser professor, junto com ele. Mais do que convidar, o professor Joaquim passou uma tarefa, pediu para esse aluno preparar algumas sugestões de temas para um curso sobre educação jurídica.

Quando o aluno apresentou sua proposta, o professor disse duas frases. A primeira foi "isso é uma psicodelia, uma maluquice". A segunda, foi "nós vamos fazer".

Humildade é isso. Humildade é quando o mestre, quando o diretor da Escola diz: o aluno pode ensinar. Humildade é, sobretudo, querer aprender.

Esse "causo" me lembrou de um verso do poeta Manoel de Barros: "Há histórias tão verdadeiras que as vezes parecem que são inventadas".

O causo que eu contei, parece inventado. A história dessa Escola, que começou em 2002 e que tem só 15 anos, parece inventada.

** Impacto

A terceira virtude que eu queria destacar é impacto. Para começar, eu queria citar um texto de 2002. Este é o texto descreve o projeto fundador da Escola. Um texto que mudou a minha vida.

Na época, eu era um aluno de Direito da UFMG. Quando eu li esse texto, as frases que me vinham à cabeça eram: "esse cara entendeu, esse cara percebeu o problema que eu vivo diariamente".

Quando eu terminei de ler esse texto, eu estava convicto que existia uma crise na educação jurídica brasileira. Eu vivia a crise que ele descrevia.

Depois de ter lido esse texto, eu tive dois sentimentos. Primeiro, esperança: uma alternativa, uma resposta para essa crise estava sendo construída no Rio de Janeiro. Segundo, eu me convenci de que eu precisava estudar na FGV DIREITO RIO.

Isso significou mudar de cidade e de estado. Para um mineiro bairrista xiita-separatista praticante, como eu, isso significa mudar de país.

Tirar a ideia do papel. Construir. Eu vejo muito valor nisso. Às vezes alguns acadêmicos esquecem que o papel e o Word aceitam qualquer coisa.

A realidade não. A realidade é muito mais complicada. Por isso, a carreira do professor Joaquim tem um legado. Um legado de concreto. Esse canudo que a gente vai pegar é um dos impactos da carreira do professor Joaquim.

** Risco

Por fim, a última virtude que eu queria destacar é habilidade de tomar risco. Tem um texto do professor muito legal sobre liderança.

Nele, o professor Joaquim diz que líder é quem tem a coragem de assumir riscos. Mas não qualquer coragem, a coragem da verdade, a coragem do futuro. Lendo esse texto, eu me lembrei de uma metáfora do Schopenhauer.

Para o Schopenhauer, o "arqueiro" fraco é aquele que erra a maior parte dos alvos. O "arqueiro" bom é aquele que acerta a maior parte dos alvos. O "arqueiro" excelente é aquele que acerta um alvo que ninguém mais acerta.

E o craque? O craque é o que acerta um alvo que ninguém tinha sequer visto. Para acertar esse alvo, que ninguém nunca tinha visto, você tem que arriscar alguns tiros no escuro. Aí o entra o risco. Professor, você é um craque.

** Música

Para fechar, eu gostaria de citar uma música, uma das minhas preferidas.

Como ela é em inglês, eu vou ler uma tradução livre minha. /My Way/, Do Meu Jeito. Escrita por Paul Anka e eternizada na voz do Frank Sinatra.

#+begin_export html
<div class="epigraph">
  <blockquote>
    <p>My Way, Do Meu Jeito</p>
  </blockquote>
  <blockquote>
    <p>Arrependimentos, eu tive alguns </p>
    <p>Mas pouquíssimos para mencionar </p>
    <p>Eu fiz o que eu devia ter feito </p>
    <p>E passei por tudo consciente </p>
    <p>Sim, em certos momentos, tenho certeza que você sabia </p>
    <p>Eu mordia mais do que eu podia mastigar </p>
    <p>Quando houve dúvida </p>
    <p>Eu enfrentei tudo </p>
    <p>De pé continuei </p>
    <p>Eu fiz tudo do meu jeito </p>
    <p>E agora, conforme as lágrimas secam </p>
    <p>Eu acho tudo tão divertido </p>
    <p>E pensar que eu fiz tudo isto </p>
    <p>E, agora, conforme as lágrimas secam </p>
    <p>Eu acho tudo tão divertido </p>
    <p>E pensar que eu fiz tudo isto </p>
    <p>E, devo dizer, sem timidez </p>
    <p>Eu fiz tudo do meu jeito </p>
    <p>Eu fiz do meu jeito </p>
  </blockquote>
</div>
#+end_export

** Palmas

Eu queria fazer um último pedido. Normalmente, quando o cara faz um bom discurso, ele recebe aplausos. Eu queria fazer diferente. Eu queria fazer, digamos, do meu jeito.

Eu queria que esse discurso fosse encerrado com uma salva de palmas. Mas não para mim. E sim para o professor Joaquim.

Pela carreira dele. Pelo que ele construiu. Pelo que ele escreveu. Por ter mudado a minha vida. Por ter mudado a vida de muitos aqui. Obrigado, professor.

** Fim
