* Aos organizadores do Conexão Mercado de 2021

** Contexto

Recentemente, recebi um convite da Solucione Consultoria para gravar
um pequeno vídeo falando sobre o /Conexão Mercado/. A Solucione é uma
instituição estudantil, uma espécie de Empresa Jr. do Direito, dos
alunos de Direito da UFMG. Todos os anos, eles organizam um evento
chamado /Conexão Mercado/.

Para quem não sabe, o /Conexão Mercado/ é uma espécie de /job fair/,
um evento para que estudantes e empregadores possam se conhecer, além
de aprender um com o outro. Inicialmente, o /Conexão Mercado/ foi uma
proposta de campanha da chapa Vira-Mundo [1] para o mandato de 2013.

Por incrível que pareça, esse que vós escreve é o idealizador desse
evento, numa ideia que surgiu no segundo semestre de 2012... E lá se
vai quase uma década! Puxa, como estou ficando velho.

Apesar de idealizador, é bom que se diga, desde já, que nunca fui o
executor. Acabei saindo da UFMG antes mesmo da primeira edição. Só
deu tempo de fazer o Vetust-up. Todos os crédios de execução do
Conexão Mercado devem ir para o Gustavo Paulinelli. Aliás, como
é sabido, executar tem muito mais valor que idealizar.

Numa lenta tarde de segunda, recebi o convite para fazer um vídeo
sobre o evento. Há algum tempo, decidi que eu escreveria toda vez que
alguém me chamasse para falar sobre algo. Além disso, eu tentaria
deixar os textos públicos, no blog. Dito isso, aqui vai!

** Ao Pedro de 19 anos

Aparentemente, o segundo sub-título já refuta o título. Cheguei à
conclusão que é difícil escrever para o pessoal da Solucione. Eu não
os conheço (e seria legal conhecê-los, com certeza, deve ter gente
interessante por lá).

Dessa forma, achei que seria mais fácil escrever para mim mesmo. Ou
melhor, para o meu eu do passado. Afinal, essa parte eu conheço
bem. E, quem sabe, talvez, com sorte, alguns dos meus conselhos para o
meu eu do passado sejam úteis para os jovens de agora.

** Primeiramente, meus parabéns

Veja bem, caso você estudasse em qualquer instituição de excelência
mundial, você não iria precisar se preocupar com esse tipo de
tarefa. Eventos como esse seriam organizados desde sempre por
profissionais pagos e regados a um coffe break que soaria como um
banquete para o universitário médio. Provavelmente, existiria um setor
inteiro de /Colocação Profissional/ (placement) apenas dedicado a esse
tipo de /conexão/ entre a sua faculdade e o /mercado/. Por sinal, esse
evento seria só uma das iniciativas nesse sentido.

Infelizmente, esse não é o caso da UFMG. Como a competição dentro da
própria vila acaba sendo muito relevante, ainda mais nessa época da
vida, não se sinta como inferior. Na USP, na UFRJ e em quase todas as
instituições de ensino brasileiras também não tem /placement/. No
máximo, são iniciativas não-institucionais como a de você.

Dado esse cenário, você merece os parabéns. A organização de eventos
como esse ser idealizada e executada por estudantes é digno de
aplausos. Aliás, esse tipo de atividade forma caráter. Nunca esqueça
que o leão magricela da savana ganha de qualquer leãozinho nutella de
zoológico. Caçar a própria comida é algo difícil de se ensinar.

** /Realpolitik/

Seria imprudente analisar como as coisas estão agora, afinal, trata-se
de um dia-a-dia que não vivencio. O que conheço é o dia-a-dia de
quase uma década atrás.

Mesmo assim, muitos não concordariam com a minha visão de como as
coisas eram no passado. E não há nenhum problema nisso. Inclusive, a
discordância não deveria censurar sobre o que pretendo discorrer.

Naquela época, o ambiente político era muito intenso na
faculdade. Existiam, pelo menos, duas dimensões da vida política, a
interna e a externa. Primeiro, na interna, discutia-se questões como o
próximo diretor, as reuniões de colegiado, novas notas de repúdio, a
inserção de catracas e etc. Na segunda, externa, discutia-se questões
da política local, estadual, nacional ou mundial. Citando exemplos
reais vistos em cartazes da época, a presença do Exército brasileiro
no Haiti e os 10% do PIB para a educação.

Há de ser ressaltado que a política é inerente a toda aglomeração de
pessoas. Afinal, ela emerge da existência de pessoas, recursos e,
claro, da escassez. No céu, não tem política (imagino). No inferno, é
uma certeza, rs.

No entanto, o que se via na Faculdade de Direito da UFMG era
completamente desproporcional. Para muitos ali, alunos e professores,
o ativismo político era a grande atividade do dia. Aulas, artigos, "a
matéria", produção científica (?) ... Era tudo uma obrigação
secundária (e pouco divertida) para esse pessoal. Bom mesmo era a /luta/!

Se trouxermos um indivíduo de Marte para a Terra, apresentássemos a
definição de dicionário de uma universidade, de um sindicato e o
levássemos à Vetusta de 2012, com certeza, ele teria dificuldade de
classificar. Uma vez, num "congresso" de Direito Trabalhista, a
plateia e os palestrantes ecoavam o canto de "Terceirização é coisa de
Patrão... Terceirazação é coisa de Patrão".

O comportamente parece adequado para torcidas em estádios ou
sindicalistas em manifestações públicas. No ambiente científico,
desperta, no mínimo, uma bandeira amarela. Bem difícil imaginar algo
assim em um Congresso de Engenharia Aeronáutica.. /Equaçãaao é coisa de patrãaao/?
Quem é doido de levantar a mão para discordar?

O ponto em comum entra as duas dimensões era a homogeniedade
ideológica. Em geral, as opiniões estavam sempre na mesma matriz
ideológica.

Apesar de toda retória de diversidade, tolerância e et cetera, existia
umas 5 opiniões diferentes. Quer dizer, vamos subir uma ordem de
magnitude, talvez, uns 50 clusters de posicionamentos. Mas, eram 50
tons de cinza. Ou melhor, de vermelho. Muito mais semelhantes do que
diferentes entre si.

Naquela época, era uma aposta intelectual segura escolher essa matriz
de pensamento. Pelo menos nesse tipo espaço. Parece que continua
sendo.

** Aprenda a ignorar

E o que a seção acima tem a ver com o /Conexão Mercado/? Bom, era
exatamente o que eu me perguntava, na época.

Acredite se quiser, o Conexão Mercado atraía muita antipatia de
poucos. Para alguns, a simples palavra /Mercado/ era uma heresia naquele
ambiente. Ela ofendia dogmas.

Curiosamente, foi o grande sucesso na campanha para a gestão de Centro
Acadêmico. Ao ouvi-la, as pessoas acordavam da sonolenta aula
anterior. Aparentemente, uma ideia que toda no fundo do aluno médio,
mas, que irritava profundamente  os mais energéticos ativistas.

A simpatia majoritária do corpo estudantil era algo que me
intrigava. Afinal, trata-se de uma ideia bem básica. Se ela é tão
simples, por que ninguém teve ela antes?

Bom, a hostilidade e os dogmas do contexto ajudam a explicar.

Uma das críticas que ouvi à época é que tal evento representava uma
*privatização* da universidade. Bom, eu não estava (e nem poderia)
vender nada ali. Na verdade, não tenho certeza sequer se existiria
algum comprador, rs. Haja vista que conhece bem, entre quatro paredes,
não compra aquilo lá.

Mas, depois de algum tempo, eu entendi. Na visão do incauto
adversário, eu estaria privatizando a universidade pública ao
submetê-la à dinâmica do mercado.

Correto. Nessa aí, ele acertou. Era essa mesmo a ideia. Agora, a
pergunta que me faltou fazer foi: E você, meu camarada, como espera
pagar os seus boletos depois que sair da casa do papai e da mamãe?

Já aviso de imediato que promotores, juízes, defensores públicos,
sindicalistas e até os advogados populares... Todos esses tem conta no
banco e pagam boletos. A economia de mercado existe. E ela aparece
rapidinho depois da entrega do canudo.

** O depois da faculdade

A vida na faculdade é bem documentada e tem uma bela estética no
imaginário popular . Pessoas jovens, saradas, felizes... Até o "tô
formando e agora" é bem documentado, haja vista uma seção só para isso
no Vetust-up, ideia do Arthur Belo. O que não tem tanta visibilidade
para quem está na faculdade é o /depois/ da faculdade. Aliás, um
fenômeno que lembra muito as descrições de bolha...

O depois da faculdade, definitivamente, não é tão legal. E, até por
isso, ele é mais obscuro - sobretudo os casos tristes. Em tempos de
auto-promoção tunada por redes sociais, eles são invisíveis.

Ainda que alguns lutem bravamente contra a economia de mercado, assim
como a gravidade, ela existe. E os boletos vem junto com
ela. Sobreviver, sem o papai e a mamãe, não é trivial. Com o conforto
igual ou superior o que foi recebido, muito menos.

Para o pessoal do Direito, no Brasil, talvez, nunca tenha sido tão
difícil quanto agora. De 1848 para cá, quando a primeira faculdade foi
criada, o /glamour/ acabou. Formar em Direito não é algo de poucos.

Além de estar no país com mais advogados do mundo, os formandos de
agora enfrentam um mercado em transformação digital. Como os ludistas
de outrora nos mostraram, não adianta quebrar as máquinas. Elas vêm
para ficar. E, historicamente, sempre criam mais empregos do que
menos, não necessariamente para o mesmo grupo de trabalhadores de uma geração.

Até o cenário de concursos públicos parece estar sob ameaça de
extinção. Criado em meados do século XX por Getúlio Vargas, a
estrutura de estabilidade acompanhada de altos salários parece
distante dos fundamentos. E da realidade do país. Vocês conhecem
alguém que trabalhando 6 horas por dia, sem ensino superior, receba
dois dígitos de salário bruto e tenha praticamente risco zero de ser
demitido?

Bom, na iniciativa privada, isso não existe. No Brasil e em nenhum
lugar do mundo. Isso é um bug. E nunca é bom apostar suas fichas. Pode
até dar certo por um tempo e para alguns. Mais cedo ou mais tarde, os
fundamentos sempre aparecem e o sistema corrige o bug, por bem ou por
mal.

Dito isso, ignore o mundo paralelo que você vive. Boa parte do que se
discute aí é completamente irrelevante fora daí. Discutir por horas no
facebook não irá te ensinar nada e, provavelmente, não mudará a
opinião de ninguém.

Se for fazer política, que faça bem feito. Com educação, elegãncia e
com bons adversários. Mas, acima de tudo, não se esqueça que, exceto
pelos políticos profissionais e os que cercam, política não paga
boletos.

Mais cedo ou mais tarde, os boletos aparecem. E é bom estar preparado
para lidar com eles. Estude muito. Entenda o mercado. Relacione-se com
o mercado. E prepara-se. /Welcome to the jungle/.





[1] não me lembro se tinha ou não o hífen.
